import { useState } from "react";
import { useSpring, animated } from "@react-spring/web";

//generated by chat2code .dev: (* clear session data, only 3 queries free) 'Create a accordion component', 'use react-spring for animation'

type AccordionProps = {
    title: string;
    children: React.ReactNode;
};

const Accordion = ({ title, children }: AccordionProps) => {
    const [isOpen, setIsOpen] = useState(false);

    const contentAnimation = useSpring({
        height: isOpen ? "auto" : 0,
        opacity: isOpen ? 1 : 0,
    });

    const handleToggle = () => {
        setIsOpen((prevIsOpen) => !prevIsOpen);
    };

    return (
        <div>
            <button
                className="flex items-center justify-between w-full px-4 py-2 text-lg font-medium text-gray-800 bg-gray-200 rounded-lg focus:outline-none hover:bg-gray-300"
                onClick={handleToggle}
            >
                <span>{title}</span>

                <svg
                    className={`w-5 h-5 transition-transform transform ${isOpen ? "rotate-180" : ""}`}
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                </svg>

            </button>

            <animated.div style={contentAnimation}>
                <div className="mt-2 px-4 py-2 bg-gray-100 rounded-lg">
                    {children}
                </div>
            </animated.div>
        </div>
    );
};

export function AccordionTest() {
    return (
        <div className="p-4">
            <Accordion title="Accordion 1">
                <p>Content for Accordion 1</p>
                <p>Content for Accordion 2</p>
                <p>Content for Accordion 3</p>
            </Accordion>

            <Accordion title="Accordion 2">
                <p>Content for Accordion 2</p>
            </Accordion>

            <Accordion title="Accordion 3">
                <p>Content for Accordion 3</p>
            </Accordion>
        </div>
    );
}
