import { ReactNode, useState } from "react";
import { useTransition, animated } from "@react-spring/web";

//generated by chat2code .dev: (* clear session data, only 3 queries free) 'Create a accordion component using react-spring for animation'

type AccordionProps = {
    title: string;
    content: string | ReactNode;
};

const Accordion: React.FC<AccordionProps> = ({ title, content }) => {
    const [isOpen, setIsOpen] = useState(false);

    const transitions = useTransition(isOpen, {
        from: { height: 0, opacity: 0 },
        enter: { height: "auto", opacity: 1, config: { duration: 4000 } },
        leave: { height: 0, opacity: 0, config: { duration: 4000 } },
    });

    return (
        <div className="border border-gray-300 rounded p-4 mb-4">
            <button
                className="flex items-center justify-between w-full text-lg font-semibold text-blue-600"
                onClick={() => setIsOpen(!isOpen)}
            >
                {title}

                <svg
                    className={`w-5 h-5 transition-transform duration-300 transform ${isOpen ? "rotate-90" : ""}`}
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                >
                    <path d="M6 9l6 6 6-6" />
                </svg>

            </button>

            {transitions(
                (style, item) => item && (
                    <animated.div style={style} className="overflow-hidden">
                        <p className="text-gray-600">
                            {content}
                        </p>
                    </animated.div>
                )
            )}
        </div>
    );
};

export function AccordionTest2() {
    return (
        <div className="">
            <Accordion
                title="Accordion Title 1"
                content={
                    <div>
                        <div className="">"Accordion Content 1"</div>
                        <div className="">"Accordion Content 1"</div>
                        <div className="">"Accordion Content 1"</div>
                        <div className="">"Accordion Content 1"</div>
                        <div className="">"Accordion Content 1"</div>
                        <div className="">"Accordion Content 1"</div>
                    </div>
                }
            />

            <Accordion title="Accordion Title 2" content="Accordion Content 2" />

            <Accordion title="Accordion Title 3" content="Accordion Content 3" />
        </div>
    );
}
